server:
  port: 8080

spring:
  application:
    name: api-gateway

  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      loadbalancer:
        retry:
          enabled: true

      routes:

        - id: student-service-route
          uri: lb://student-service
          predicates:
            - Path=/student/**

        - id: topic-service-route
          uri: lb://topic-service
          predicates:
            - Path=/topic/**

        - id: iam-service-route
          uri: lb://iam-service
          predicates:
            - Path=/api/auth/**


eureka:
  client:
    healthcheck:
      enabled: true

    fetch-registry: true

    register-with-eureka: true

    service-url:
      default-zone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true

    lease-renewal-interval-in-seconds: 5

    lease-expiration-duration-in-seconds: 10


management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    info:
      enabled: true
